In [ ]:
!pip install torchmetrics

In [ ]:
import torch

In [ ]:
import torchmetrics

In [ ]:
#Creating Tensors
tensor_a = torch.tensor([[1,2],[3,4]])
tensor_b = torch.tensor([[5,6],[7,8]])

In [ ]:
print(f'Tensor A: ',tensor_a,'\nTensor B:',tensor_b)

Tensor A:  tensor([[1, 2],
        [3, 4]]) 
Tensor B: tensor([[5, 6],
        [7, 8]])


In [ ]:
# Addition
addtion_results = torch.add(tensor_a,tensor_b)
print(f'Addtion of the Tensor A and Tensor B is: ',addtion_results)

Addtion of the Tensor A and Tensor B is:  tensor([[ 6,  8],
        [10, 12]])


In [ ]:
# Subtraction
subtraction_results = torch.sub(tensor_a,tensor_b)
print(f'Subtraction of the Tensor A and Tensor B is: ',subtraction_results)

Subtraction of the Tensor A and Tensor B is:  tensor([[-4, -4],
        [-4, -4]])


In [ ]:
# Element wise Multiplication
element_wise_multi = torch.mul(tensor_a,tensor_b)
print(f'Elementwise Multiplication of the Tensor A and Tensor B is: ',element_wise_multi)

Elementwise Multiplication of the Tensor A and Tensor B is:  tensor([[ 5, 12],
        [21, 32]])


In [ ]:
# Matrix Multiplication
mat_mul_results = torch.mm(tensor_a,tensor_b)
print(f'Matrix Multiplication of the Tensor A and Tensor B is: ',mat_mul_results)

Matrix Multiplication of the Tensor A and Tensor B is:  tensor([[19, 22],
        [43, 50]])


In [ ]:
#Transpose
transpose_result = torch.transpose(tensor_a, 0, 1)
print(f'Transpose of the Tensor A is: ',transpose_result)

Transpose of the Tensor is:  tensor([[1, 3],
        [2, 4]])


In [ ]:
# Elementwise Division
elementwise_divide_result = torch.div(tensor_a, tensor_b.float())
print(f'Elementwise division of tensor A and Tensor B is: ',elementwise_divide_result)

Elementwise division of tensor A and Tensor B is:  tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


In [ ]:
# TORCH.ARANGE
#torch.arange(5)
#torch.arange(1,10)
torch.arange(1,10,0.5)

tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000, 4.5000, 5.0000,
        5.5000, 6.0000, 6.5000, 7.0000, 7.5000, 8.0000, 8.5000, 9.0000, 9.5000])

In [ ]:
i = torch.tensor([[0, 1, 1],
                  [2, 0, 2]])
v = torch.tensor([3, 4, 5], dtype=torch.float32)

# Create a sparse COO tensor with specified size [2, 4]
sparse_coo_tensor_1 = torch.sparse_coo_tensor(i, v, [2, 4])

print("Sparse COO Tensor 1:")
print(sparse_coo_tensor_1)

# Create a sparse COO tensor without specifying size
sparse_coo_tensor_2 = torch.sparse_coo_tensor(i, v)
print("\nSparse COO Tensor 2:")
print(sparse_coo_tensor_2)


Sparse COO Tensor 1:
tensor(indices=tensor([[0, 1, 1],
                       [2, 0, 2]]),
       values=tensor([3., 4., 5.]),
       size=(2, 4), nnz=3, layout=torch.sparse_coo)

Sparse COO Tensor 2:
tensor(indices=tensor([[0, 1, 1],
                       [2, 0, 2]]),
       values=tensor([3., 4., 5.]),
       size=(2, 3), nnz=3, layout=torch.sparse_coo)


In [ ]:
# TORCH.NUMEL
tensor_c =torch.randn(1,100)
torch.numel(tensor_c)

100

In [ ]:
#Elementwise exponentiation
elementwise_exp_result = torch.exp(tensor_a.float())
print(f'Elementwise Exponential of Tensor_a is :',elementwise_exp_result )

Elementwise Exponential of Tensor_a is : tensor([[ 2.7183,  7.3891],
        [20.0855, 54.5981]])


In [ ]:
# Concatenation along a dimension
concatenation_result = torch.cat((tensor_a, tensor_b), dim=0)
print(f'Concatenation along a dimension :',concatenation_result )

Concatenation along a dimension : tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [ ]:
# Reshape tensor
reshaped_result = tensor_a.view(-1)
print(f'reshaped_result :',reshaped_result )

reshaped_result : tensor([1, 2, 3, 4])


In [ ]:
#Elementwise greater than
elementwise_greater_than_result = torch.gt(tensor_a, tensor_b)

#Elementwise less than
elementwise_less_than_result = torch.lt(tensor_a, tensor_b)
print("\nElementwise Greater Than Result:")
print(elementwise_greater_than_result)
print("\nElementwise Less Than Result:")
print(elementwise_less_than_result)


Elementwise Greater Than Result:
tensor([[False, False],
        [False, False]])

Elementwise Less Than Result:
tensor([[True, True],
        [True, True]])


In [ ]:
tensor_a = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
tensor_b = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

In [ ]:
#Matrix determinant
matrix_determinant = torch.det(tensor_a)
print("Matrix Determinant:")
print(matrix_determinant)


Matrix Determinant:
tensor(-2.)


In [ ]:
#TORCH.FULL
torch.full((2,2),5)

tensor([[5, 5],
        [5, 5]])

In [ ]:
#TORCH.MASKED_SELECT
tensor_d = torch.rand(2,2)
print(tensor_d,'\n')
mask = tensor_d.ge(0.5)
print(mask,'\n')
selected_values = torch.masked_select(tensor_d, mask)
print(selected_values)

tensor([[0.2868, 0.0913],
        [0.5726, 0.6436]]) 

tensor([[False, False],
        [ True,  True]]) 

tensor([0.5726, 0.6436])


In [ ]:
# Batch matrix multiplication
batched_matrix_a = torch.rand(3, 2, 2)
batched_matrix_b = torch.rand(3, 2, 2)
print(batched_matrix_a,'\n',batched_matrix_b,'\n')
batched_matrix_multiply_result = torch.bmm(batched_matrix_a, batched_matrix_b)
print("\nBatch Matrix Multiplication Result:")
print(batched_matrix_multiply_result)

tensor([[[0.8176, 0.9138],
         [0.2785, 0.1611]],

        [[0.9226, 0.8993],
         [0.0601, 0.2610]],

        [[0.2041, 0.5310],
         [0.8635, 0.5005]]]) 
 tensor([[[0.7942, 0.3209],
         [0.1028, 0.8022]],

        [[0.4398, 0.6017],
         [0.8370, 0.5187]],

        [[0.0945, 0.6098],
         [0.7600, 0.8448]]]) 


Batch Matrix Multiplication Result:
tensor([[[0.7432, 0.9955],
         [0.2377, 0.2186]],

        [[1.1584, 1.0215],
         [0.2449, 0.1715]],

        [[0.4228, 0.5730],
         [0.4620, 0.9493]]])


In [ ]:
# TORCH.VSPLIT
# Create a 4x4 tensor
t = torch.arange(16.0).reshape(4, 4)
print(t)

# Split the tensor into two along the rows
split_result_1 = torch.vsplit(t, 2)
print(split_result_1)

# Split the tensor into three along the rows with specified indices
split_result_2 = torch.vsplit(t, [3, 6])
print(split_result_2)


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])
(tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]), tensor([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]))
(tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]), tensor([[12., 13., 14., 15.]]), tensor([], size=(0, 4)))


In [ ]:
#Repeat tensor along a dimension
repeated_tensor = tensor_a.repeat(2, 3)
print("\nRepeated Tensor:")
print(repeated_tensor)


Repeated Tensor:
tensor([[1., 2., 1., 2., 1., 2.],
        [3., 4., 3., 4., 3., 4.],
        [1., 2., 1., 2., 1., 2.],
        [3., 4., 3., 4., 3., 4.]])


In [ ]:
tensor_e = torch.tensor([[2,3,4],[5,2,1]])

# Cumulative product along a dimension
cumulative_product_result = torch.cumprod(tensor_e, dim=1)
print("\nCumulative Product Result:")
print(cumulative_product_result)


Cumulative Product Result:
tensor([[ 2,  6, 24],
        [ 5, 10, 10]])


In [ ]:
# TORCH.PERMUTE
x = torch.randn(2, 3, 5)
print(x)
print(x.size(),'\n')

torch.permute(x, (2, 0, 1))

tensor([[[ 1.5880,  0.7639,  0.5755,  0.2814, -0.2978],
         [ 0.5198, -0.9649, -0.7114, -0.7560,  0.8767],
         [-0.3643,  0.2914,  1.1468,  0.7619, -0.7350]],

        [[ 0.2616,  1.0866,  0.5497,  0.8726, -0.6225],
         [ 0.6467,  0.6140, -0.2402,  0.7382, -0.1878],
         [ 0.8570, -0.4697,  0.6649, -0.3207,  1.0428]]])
torch.Size([2, 3, 5]) 



tensor([[[ 1.5880,  0.5198, -0.3643],
         [ 0.2616,  0.6467,  0.8570]],

        [[ 0.7639, -0.9649,  0.2914],
         [ 1.0866,  0.6140, -0.4697]],

        [[ 0.5755, -0.7114,  1.1468],
         [ 0.5497, -0.2402,  0.6649]],

        [[ 0.2814, -0.7560,  0.7619],
         [ 0.8726,  0.7382, -0.3207]],

        [[-0.2978,  0.8767, -0.7350],
         [-0.6225, -0.1878,  1.0428]]])

In [ ]:
# Define a condition and two tensors
condition = torch.tensor([[True, False], [False, True]])
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])

# Use torch.where to select elements based on the condition
result = torch.where(condition, x, y)
print(result)


tensor([[1, 6],
        [7, 4]])


In [ ]:
import torch.nn.functional as F

# Define a tensor
input_tensor = torch.tensor([[1, 2, 3],
                             [4, 5, 6]])

# Apply zero-padding using F.pad
padded_tensor = F.pad(input_tensor, (1, 2))
print(padded_tensor)

tensor([[0, 1, 2, 3, 0, 0],
        [0, 4, 5, 6, 0, 0]])


In [ ]:
# Create a tensor
input_tensor = torch.tensor([[3, 1, 4], [1, 5, 9]])

# Find the indices of the maximum values along a specified axis (default: last axis)
max_indices = torch.argmax(input_tensor)
print(max_indices)


tensor(5)


In [ ]:
# Define a tensor and create a computation graph
x = torch.tensor(2.0, requires_grad=True)
y = x ** 2
z = y + 3

# Compute the gradient of z with respect to x using torch.autograd.grad
gradient = torch.autograd.grad(z, x)
print("Gradient:", gradient[0].item())


Gradient: 4.0
